name:                LRCRPC
version:             0.1.0.0
github:              "pe200012/LRCRPC"
license:             BSD3
author:              "pe200012"
maintainer:          "1326263755@qq.com"
copyright:           "Apache-2.0"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pe200012/LRCRPC#readme>

dependencies:
- base >= 4.7 && < 5
- microlens
- capnp

library:
  source-dirs: src

executables:
  LRCRPC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LRCRPC

tests:
  LRCRPC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LRCRPC
